name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  microsoft_kiota_abstractions: ^0.0.2
  microsoft_kiota_bundle: ^0.0.3
  microsoft_kiota_http: ^0.0.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
